# Generated by Django 5.0.14 on 2026-08-17 10:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIndicateur',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('libelle', models.CharField(max_length=300)),
                ('unite', models.CharField(max_length=50)),
                ('valeur_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valeur_reference_date', models.DateField(blank=True, null=True)),
                ('valeur_cible', models.DecimalField(decimal_places=2, max_digits=14)),
                ('frequence_collecte', models.CharField(choices=[('MENSUELLE', 'Mensuelle'), ('TRIMESTRIELLE', 'Trimestrielle'), ('SEMESTRIELLE', 'Semestrielle'), ('ANNUELLE', 'Annuelle')], max_length=20)),
                ('source_verification', models.CharField(blank=True, max_length=300)),
                ('seuil_alerte_jaune', models.PositiveSmallIntegerField(default=80, help_text="Taux de réalisation (%) en-dessous duquel l'indicateur passe en alerte jaune.")),
                ('seuil_alerte_rouge', models.PositiveSmallIntegerField(default=50, help_text="Taux de réalisation (%) en-dessous duquel l'indicateur passe en alerte rouge.")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('activite', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.activite')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('objectif_specifique', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.objectifspecifique')),
            ],
            options={
                'verbose_name': 'historical indicateur',
                'verbose_name_plural': 'historical indicateurs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=300)),
                ('unite', models.CharField(max_length=50)),
                ('valeur_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valeur_reference_date', models.DateField(blank=True, null=True)),
                ('valeur_cible', models.DecimalField(decimal_places=2, max_digits=14)),
                ('frequence_collecte', models.CharField(choices=[('MENSUELLE', 'Mensuelle'), ('TRIMESTRIELLE', 'Trimestrielle'), ('SEMESTRIELLE', 'Semestrielle'), ('ANNUELLE', 'Annuelle')], max_length=20)),
                ('source_verification', models.CharField(blank=True, max_length=300)),
                ('seuil_alerte_jaune', models.PositiveSmallIntegerField(default=80, help_text="Taux de réalisation (%) en-dessous duquel l'indicateur passe en alerte jaune.")),
                ('seuil_alerte_rouge', models.PositiveSmallIntegerField(default=50, help_text="Taux de réalisation (%) en-dessous duquel l'indicateur passe en alerte rouge.")),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicateurs', to='projects.activite')),
                ('objectif_specifique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicateurs', to='projects.objectifspecifique')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalValeurIndicateur',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('valeur_realisee', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_saisie', models.DateTimeField(blank=True, editable=False)),
                ('commentaire', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('saisi_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('indicateur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.indicateur')),
            ],
            options={
                'verbose_name': "historical Valeur d'indicateur",
                'verbose_name_plural': "historical Valeurs d'indicateur",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ValeurIndicateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('valeur_realisee', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('indicateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valeurs', to='indicators.indicateur')),
                ('saisi_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valeurs_indicateurs_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Valeur d'indicateur",
                'verbose_name_plural': "Valeurs d'indicateur",
                'ordering': ('-periode_fin',),
            },
        ),
        migrations.AddConstraint(
            model_name='indicateur',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('activite__isnull', True), ('objectif_specifique__isnull', False)), models.Q(('activite__isnull', False), ('objectif_specifique__isnull', True)), _connector='OR'), name='indicateur_rattachement_unique'),
        ),
        migrations.AddConstraint(
            model_name='valeurindicateur',
            constraint=models.UniqueConstraint(fields=('indicateur', 'periode_debut', 'periode_fin'), name='valeur_indicateur_periode_unique'),
        ),
    ]
