# Generated by Django 5.0.14 on 2026-08-17 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
        ('projects', '0002_activite_axe_strategique_activite_budget_realise_and_more'),
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='indicateur',
            name='indicateur_rattachement_unique',
        ),
        migrations.AddField(
            model_name='historicalindicateur',
            name='axe_strategique_alimente',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Si renseigné, cet indicateur alimente aussi le cadre de mesure des performances de cet axe stratégique.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='strategy.axestrategique'),
        ),
        migrations.AddField(
            model_name='historicalindicateur',
            name='objectif_general',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.objectifgeneral'),
        ),
        migrations.AddField(
            model_name='historicalindicateur',
            name='plan_strategique',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='strategy.planstrategique'),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='axe_strategique_alimente',
            field=models.ForeignKey(blank=True, help_text='Si renseigné, cet indicateur alimente aussi le cadre de mesure des performances de cet axe stratégique.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicateurs_alimentes', to='strategy.axestrategique'),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='objectif_general',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicateurs', to='projects.objectifgeneral'),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='plan_strategique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicateurs', to='strategy.planstrategique'),
        ),
        migrations.AddConstraint(
            model_name='indicateur',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('activite__isnull', True), ('objectif_general__isnull', True), ('objectif_specifique__isnull', True), ('plan_strategique__isnull', False)), models.Q(('activite__isnull', True), ('objectif_general__isnull', False), ('objectif_specifique__isnull', True), ('plan_strategique__isnull', True)), models.Q(('activite__isnull', True), ('objectif_general__isnull', True), ('objectif_specifique__isnull', False), ('plan_strategique__isnull', True)), models.Q(('activite__isnull', False), ('objectif_general__isnull', True), ('objectif_specifique__isnull', True), ('plan_strategique__isnull', True)), _connector='OR'), name='indicateur_rattachement_unique'),
        ),
    ]
