# Generated by Django 5.0.14 on 2026-08-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_remove_indicateur_indicateur_rattachement_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicateurElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='indicateur',
            name='indicateur_rattachement_unique',
        ),
        migrations.RemoveField(
            model_name='historicalindicateur',
            name='axe_strategique_alimente',
        ),
        migrations.RemoveField(
            model_name='historicalindicateur',
            name='plan_strategique',
        ),
        migrations.RemoveField(
            model_name='indicateur',
            name='axe_strategique_alimente',
        ),
        migrations.RemoveField(
            model_name='indicateur',
            name='plan_strategique',
        ),
    ]
