# Generated by Django 5.0.14 on 2026-08-18 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_indicateurelement_and_more'),
        ('projects', '0004_alter_activite_axe_strategique_and_more'),
        ('strategy', '0003_delete_axestrategique_delete_orientationstrategique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateurelement',
            name='element_strategique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicateur_elements', to='strategy.elementstrategique'),
        ),
        migrations.AddField(
            model_name='indicateurelement',
            name='indicateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicateur_elements', to='indicators.indicateur'),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='elements_strategiques',
            field=models.ManyToManyField(blank=True, related_name='indicateurs', through='indicators.IndicateurElement', to='strategy.elementstrategique'),
        ),
        migrations.AddConstraint(
            model_name='indicateur',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('activite__isnull', True), ('objectif_general__isnull', True), ('objectif_specifique__isnull', True)), models.Q(('activite__isnull', True), ('objectif_general__isnull', False), ('objectif_specifique__isnull', True)), models.Q(('activite__isnull', True), ('objectif_general__isnull', True), ('objectif_specifique__isnull', False)), models.Q(('activite__isnull', False), ('objectif_general__isnull', True), ('objectif_specifique__isnull', True)), _connector='OR'), name='indicateur_rattachement_au_plus_un'),
        ),
        migrations.AddConstraint(
            model_name='indicateurelement',
            constraint=models.UniqueConstraint(fields=('indicateur', 'element_strategique'), name='indicateur_element_unique'),
        ),
    ]
