# Generated by Django 5.0.14 on 2026-08-19 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_indicateurelement_element_strategique_and_more'),
        ('projects', '0016_equipe_dates_contrat'),
        ('strategy', '0007_typeniveau_cadre_strategique_required'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='indicateur',
            name='indicateur_rattachement_au_plus_un',
        ),
        migrations.RemoveField(
            model_name='historicalindicateur',
            name='source_verification',
        ),
        migrations.RemoveField(
            model_name='indicateur',
            name='source_verification',
        ),
        migrations.AddField(
            model_name='historicalindicateur',
            name='projet',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.projet'),
        ),
        migrations.AddField(
            model_name='indicateur',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicateurs', to='projects.projet'),
        ),
        migrations.AddConstraint(
            model_name='indicateur',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('activite__isnull', True), ('objectif_general__isnull', True), ('objectif_specifique__isnull', True), ('projet__isnull', True)), models.Q(('activite__isnull', True), ('objectif_general__isnull', True), ('objectif_specifique__isnull', True), ('projet__isnull', False)), models.Q(('activite__isnull', True), ('objectif_general__isnull', False), ('objectif_specifique__isnull', True), ('projet__isnull', True)), models.Q(('activite__isnull', True), ('objectif_general__isnull', True), ('objectif_specifique__isnull', False), ('projet__isnull', True)), models.Q(('activite__isnull', False), ('objectif_general__isnull', True), ('objectif_specifique__isnull', True), ('projet__isnull', True)), _connector='OR'), name='indicateur_rattachement_au_plus_un'),
        ),
    ]
