# Generated by Django 5.0.14 on 2026-08-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_projet_direct_et_retrait_source_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seuil_jaune_defaut', models.PositiveSmallIntegerField(default=80, help_text='Taux (%) par défaut en-dessous duquel un nouvel indicateur passe dans le palier intermédiaire.')),
                ('seuil_rouge_defaut', models.PositiveSmallIntegerField(default=50, help_text='Taux (%) par défaut en-dessous duquel un nouvel indicateur passe dans le palier le plus bas.')),
                ('libelle_vert', models.CharField(default='Conforme', max_length=50)),
                ('libelle_jaune', models.CharField(default='À risque', max_length=50)),
                ('libelle_rouge', models.CharField(default='Critique', max_length=50)),
            ],
            options={
                'verbose_name': "Paramètres d'alerte",
                'verbose_name_plural': "Paramètres d'alerte",
            },
        ),
    ]
