# Generated by Django 5.0.14 on 2026-08-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_parametresalerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresalerte',
            name='couleur_jaune',
            field=models.CharField(default='#fab219', help_text='Couleur hexadécimale (ex : #fab219).', max_length=7),
        ),
        migrations.AddField(
            model_name='parametresalerte',
            name='couleur_rouge',
            field=models.CharField(default='#d03b3b', help_text='Couleur hexadécimale (ex : #d03b3b).', max_length=7),
        ),
        migrations.AddField(
            model_name='parametresalerte',
            name='couleur_vert',
            field=models.CharField(default='#0ca30c', help_text='Couleur hexadécimale (ex : #0ca30c).', max_length=7),
        ),
    ]
