# Generated by Django 5.0.14 on 2026-08-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_parametresalerte_couleur_jaune_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresalerte',
            name='seuil_echeance_jours',
            field=models.PositiveSmallIntegerField(default=7, help_text="Nombre de jours avant une échéance (activité, sous-activité, projet) à partir duquel une alerte de rappel est envoyée — l'échéance déjà dépassée alerte toujours, quel que soit ce seuil."),
        ),
    ]
