# Generated by Django 5.0.14 on 2026-08-21 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_parametresalerte_seuil_echeance_jours'),
        ('projects', '0018_activite_valeur_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalindicateur',
            name='seuil_alerte_jaune',
        ),
        migrations.RemoveField(
            model_name='historicalindicateur',
            name='seuil_alerte_rouge',
        ),
        migrations.RemoveField(
            model_name='indicateur',
            name='seuil_alerte_jaune',
        ),
        migrations.RemoveField(
            model_name='indicateur',
            name='seuil_alerte_rouge',
        ),
        migrations.RemoveField(
            model_name='parametresalerte',
            name='couleur_jaune',
        ),
        migrations.RemoveField(
            model_name='parametresalerte',
            name='couleur_rouge',
        ),
        migrations.RemoveField(
            model_name='parametresalerte',
            name='couleur_vert',
        ),
        migrations.RemoveField(
            model_name='parametresalerte',
            name='libelle_jaune',
        ),
        migrations.RemoveField(
            model_name='parametresalerte',
            name='libelle_rouge',
        ),
        migrations.RemoveField(
            model_name='parametresalerte',
            name='libelle_vert',
        ),
        migrations.RemoveField(
            model_name='parametresalerte',
            name='seuil_jaune_defaut',
        ),
        migrations.RemoveField(
            model_name='parametresalerte',
            name='seuil_rouge_defaut',
        ),
        migrations.CreateModel(
            name='PalierAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borne_min', models.PositiveSmallIntegerField(help_text="Taux de réalisation (%) à partir duquel ce palier s'applique.")),
                ('libelle', models.CharField(max_length=50)),
                ('couleur', models.CharField(help_text='Couleur hexadécimale (ex : #0ca30c).', max_length=7)),
                ('projet', models.ForeignKey(blank=True, help_text='Vide = palier de la palette globale par défaut (utilisée par les projets sans palette propre).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paliers_alerte', to='projects.projet')),
            ],
            options={
                'verbose_name': "Palier d'alerte",
                'verbose_name_plural': "Paliers d'alerte",
                'ordering': ('projet_id', 'borne_min'),
            },
        ),
        migrations.AddConstraint(
            model_name='palieralerte',
            constraint=models.UniqueConstraint(fields=('projet', 'borne_min'), name='palier_alerte_projet_borne_unique'),
        ),
    ]
