# Generated by Django 5.0.14 on 2026-08-21 17:14
"""
Reprend, comme palette globale par défaut (PalierAlerte.projet=None), les
3 paliers auparavant fixés en dur (ParametresAlerte.libelle_*/couleur_*) —
tout projet sans palette propre continue de voir les mêmes libellés/couleurs
qu'avant ce changement.
"""
from django.db import migrations


def seed_palette(apps, schema_editor):
    PalierAlerte = apps.get_model("indicators", "PalierAlerte")
    if PalierAlerte.objects.filter(projet__isnull=True).exists():
        return
    PalierAlerte.objects.bulk_create(
        [
            PalierAlerte(projet=None, borne_min=0, libelle="Critique", couleur="#d03b3b"),
            PalierAlerte(projet=None, borne_min=50, libelle="À risque", couleur="#fab219"),
            PalierAlerte(projet=None, borne_min=80, libelle="Conforme", couleur="#0ca30c"),
        ]
    )


def revert(apps, schema_editor):
    PalierAlerte = apps.get_model("indicators", "PalierAlerte")
    PalierAlerte.objects.filter(projet__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_remove_historicalindicateur_seuil_alerte_jaune_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_palette, revert),
    ]
