# Generated by Django 5.0.14 on 2026-08-21 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0010_seed_palette_globale_par_defaut'),
        ('projects', '0018_activite_valeur_reference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='palieralerte',
            options={'ordering': ('projet_id', 'indicateur_id', 'activite_id', 'borne_min'), 'verbose_name': "Palier d'alerte", 'verbose_name_plural': "Paliers d'alerte"},
        ),
        migrations.RemoveConstraint(
            model_name='palieralerte',
            name='palier_alerte_projet_borne_unique',
        ),
        migrations.AddField(
            model_name='palieralerte',
            name='activite',
            field=models.ForeignKey(blank=True, help_text='Grille propre à cette activité précise, prioritaire sur celle de son projet.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paliers_alerte', to='projects.activite'),
        ),
        migrations.AddField(
            model_name='palieralerte',
            name='indicateur',
            field=models.ForeignKey(blank=True, help_text='Grille propre à cet indicateur précis, prioritaire sur celle de son projet.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paliers_alerte', to='indicators.indicateur'),
        ),
        migrations.AlterField(
            model_name='palieralerte',
            name='projet',
            field=models.ForeignKey(blank=True, help_text='Grille propre à ce projet (utilisée par ses indicateurs/activités sans grille propre).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paliers_alerte', to='projects.projet'),
        ),
        migrations.AddConstraint(
            model_name='palieralerte',
            constraint=models.UniqueConstraint(fields=('projet', 'indicateur', 'activite', 'borne_min'), name='palier_alerte_portee_borne_unique'),
        ),
        migrations.AddConstraint(
            model_name='palieralerte',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('activite__isnull', True), ('indicateur__isnull', True), ('projet__isnull', False)), models.Q(('activite__isnull', True), ('indicateur__isnull', False), ('projet__isnull', True)), models.Q(('activite__isnull', False), ('indicateur__isnull', True), ('projet__isnull', True)), models.Q(('activite__isnull', True), ('indicateur__isnull', True), ('projet__isnull', True)), _connector='OR'), name='palier_alerte_une_seule_portee'),
        ),
    ]
