# Generated by Django 5.0.14 on 2026-08-17 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_zone_type'),
        ('projects', '0001_initial'),
        ('strategy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='axe_strategique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='strategy.axestrategique'),
        ),
        migrations.AddField(
            model_name='activite',
            name='budget_realise',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='activite',
            name='code_activite',
            field=models.CharField(blank=True, help_text='Codification interne (ex : AI1.1, AI1.1.2).', max_length=30),
        ),
        migrations.AddField(
            model_name='activite',
            name='date_debut_reelle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activite',
            name='date_fin_reelle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activite',
            name='equipe_responsable',
            field=models.ManyToManyField(blank=True, related_name='activites_equipe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activite',
            name='nb_jours_planifies',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activite',
            name='quantite_prevue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='activite',
            name='quantite_realisee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='activite',
            name='statut',
            field=models.CharField(choices=[('NON_REALISEE', 'Non réalisée'), ('EN_COURS', 'En cours'), ('REALISEE', 'Réalisée')], default='NON_REALISEE', max_length=20),
        ),
        migrations.AddField(
            model_name='activite',
            name='unite_quantite',
            field=models.CharField(blank=True, help_text='Ex : producteurs, hectares, sessions…', max_length=50),
        ),
        migrations.AddField(
            model_name='activite',
            name='zones',
            field=models.ManyToManyField(blank=True, related_name='activites', to='geo.zone'),
        ),
        migrations.AddField(
            model_name='historicalactivite',
            name='axe_strategique',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='strategy.axestrategique'),
        ),
        migrations.AddField(
            model_name='historicalactivite',
            name='budget_realise',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='historicalactivite',
            name='code_activite',
            field=models.CharField(blank=True, help_text='Codification interne (ex : AI1.1, AI1.1.2).', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalactivite',
            name='date_debut_reelle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalactivite',
            name='date_fin_reelle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalactivite',
            name='nb_jours_planifies',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalactivite',
            name='quantite_prevue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalactivite',
            name='quantite_realisee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalactivite',
            name='statut',
            field=models.CharField(choices=[('NON_REALISEE', 'Non réalisée'), ('EN_COURS', 'En cours'), ('REALISEE', 'Réalisée')], default='NON_REALISEE', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalactivite',
            name='unite_quantite',
            field=models.CharField(blank=True, help_text='Ex : producteurs, hectares, sessions…', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='cible_femmes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='cible_hommes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='cible_jeunes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='cible_pdi',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cible PDI'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='cible_totale',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='elements_capitalisation',
            field=models.TextField(blank=True, help_text='Saisi en fin de projet : leçons apprises, bonnes pratiques.'),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='fonds_propres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='type_mise_en_oeuvre',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('CONSORTIUM', 'En consortium')], default='DIRECT', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalsousactivite',
            name='axe_strategique',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='strategy.axestrategique'),
        ),
        migrations.AddField(
            model_name='historicalsousactivite',
            name='quantite_prevue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalsousactivite',
            name='quantite_realisee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalsousactivite',
            name='unite_quantite',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projet',
            name='axes_strategiques',
            field=models.ManyToManyField(blank=True, related_name='projets', to='strategy.axestrategique'),
        ),
        migrations.AddField(
            model_name='projet',
            name='cible_femmes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='cible_hommes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='cible_jeunes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='cible_pdi',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cible PDI'),
        ),
        migrations.AddField(
            model_name='projet',
            name='cible_totale',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='elements_capitalisation',
            field=models.TextField(blank=True, help_text='Saisi en fin de projet : leçons apprises, bonnes pratiques.'),
        ),
        migrations.AddField(
            model_name='projet',
            name='fonds_propres',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='projet',
            name='type_mise_en_oeuvre',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('CONSORTIUM', 'En consortium')], default='DIRECT', max_length=20),
        ),
        migrations.AddField(
            model_name='sousactivite',
            name='axe_strategique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_activites', to='strategy.axestrategique'),
        ),
        migrations.AddField(
            model_name='sousactivite',
            name='quantite_prevue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sousactivite',
            name='quantite_realisee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sousactivite',
            name='unite_quantite',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='activite',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text="Responsable principal de l'activité.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activites_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalactivite',
            name='responsable',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Responsable principal de l'activité.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalprojet',
            name='budget_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Coût total = fonds propres + financements bailleurs.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='projet',
            name='budget_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Coût total = fonds propres + financements bailleurs.', max_digits=14),
        ),
    ]
