# Generated by Django 5.0.14 on 2026-08-17 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_activite_axe_strategique_activite_budget_realise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojet',
            name='chef_de_projet_nom',
            field=models.CharField(blank=True, help_text="Nom du chef de projet — texte libre, indépendant d'un compte plateforme.", max_length=200),
        ),
        migrations.AddField(
            model_name='projet',
            name='chef_de_projet_nom',
            field=models.CharField(blank=True, help_text="Nom du chef de projet — texte libre, indépendant d'un compte plateforme.", max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalprojet',
            name='chef_de_projet',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Compte plateforme lié (optionnel) — nécessaire pour que le chef de projet voie ce projet automatiquement et reçoive ses notifications.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projet',
            name='chef_de_projet',
            field=models.ForeignKey(blank=True, help_text='Compte plateforme lié (optionnel) — nécessaire pour que le chef de projet voie ce projet automatiquement et reçoive ses notifications.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projets_diriges', to=settings.AUTH_USER_MODEL),
        ),
    ]
