# Generated by Django 5.0.14 on 2026-08-18 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_historicalprojet_chef_de_projet_nom_and_more'),
        ('strategy', '0002_remove_axestrategique_orientation_strategique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='axe_strategique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='strategy.elementstrategique'),
        ),
        migrations.AlterField(
            model_name='historicalactivite',
            name='axe_strategique',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='strategy.elementstrategique'),
        ),
        migrations.AlterField(
            model_name='historicalsousactivite',
            name='axe_strategique',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='strategy.elementstrategique'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='axes_strategiques',
            field=models.ManyToManyField(blank=True, related_name='projets', to='strategy.elementstrategique'),
        ),
        migrations.AlterField(
            model_name='sousactivite',
            name='axe_strategique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_activites', to='strategy.elementstrategique'),
        ),
    ]
