# Generated by Django 5.0.14 on 2026-08-18 15:00

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_activite_axe_strategique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojet',
            name='pays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, help_text="Codes ISO 3166-1 alpha-2 des pays d'intervention (ex : BF, ML, NE).", size=None),
        ),
        migrations.AddField(
            model_name='projet',
            name='pays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, help_text="Codes ISO 3166-1 alpha-2 des pays d'intervention (ex : BF, ML, NE).", size=None),
        ),
        migrations.AlterField(
            model_name='objectifgeneral',
            name='projet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='objectif_general', to='projects.projet'),
        ),
    ]
