# Generated by Django 5.0.14 on 2026-08-18 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_historicalprojet_pays_projet_pays_and_more'),
        ('strategy', '0007_typeniveau_cadre_strategique_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='axes_strategiques',
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='cadre_strategique',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Cadre stratégique auquel ce projet est rattaché — borne les éléments stratégiques proposés pour ses activités.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='strategy.cadrestrategique'),
        ),
        migrations.AddField(
            model_name='projet',
            name='cadre_strategique',
            field=models.ForeignKey(blank=True, help_text='Cadre stratégique auquel ce projet est rattaché — borne les éléments stratégiques proposés pour ses activités.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='strategy.cadrestrategique'),
        ),
    ]
