# Generated by Django 5.0.14 on 2026-08-18 17:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projet_cadre_strategique_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='responsable_nom',
            field=models.CharField(blank=True, help_text="Nom du responsable principal — texte libre, indépendant d'un compte plateforme.", max_length=200),
        ),
        migrations.AddField(
            model_name='historicalactivite',
            name='responsable_nom',
            field=models.CharField(blank=True, help_text="Nom du responsable principal — texte libre, indépendant d'un compte plateforme.", max_length=200),
        ),
        migrations.RemoveField(
            model_name='activite',
            name='equipe_responsable',
        ),
        migrations.AlterField(
            model_name='activite',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Compte plateforme lié (optionnel) — nécessaire pour que le responsable reçoive des notifications.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activites_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalactivite',
            name='responsable',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Compte plateforme lié (optionnel) — nécessaire pour que le responsable reçoive des notifications.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('membres', models.ManyToManyField(blank=True, related_name='equipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
            },
        ),
        migrations.AddField(
            model_name='historicalactivite',
            name='equipe_responsable',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.equipe'),
        ),
        migrations.CreateModel(
            name='HistoricalEquipe',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('nom', models.CharField(db_index=True, max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Équipe',
                'verbose_name_plural': 'historical Équipes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='activite',
            name='equipe_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='projects.equipe'),
        ),
    ]
