# Generated by Django 5.0.14 on 2026-08-19 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_equipe_et_responsable_libre'),
        ('strategy', '0007_typeniveau_cadre_strategique_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojet',
            name='cadre_strategique',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Cadre stratégique auquel ce projet est rattaché — borne les éléments stratégiques proposés pour ses activités. Fortement recommandé mais pas obligatoire.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='strategy.cadrestrategique'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='cadre_strategique',
            field=models.ForeignKey(blank=True, help_text='Cadre stratégique auquel ce projet est rattaché — borne les éléments stratégiques proposés pour ses activités. Fortement recommandé mais pas obligatoire.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='strategy.cadrestrategique'),
        ),
    ]
