# Generated by Django 5.0.14 on 2026-08-19 09:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_cadre_strategique_optionnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='responsable_nom',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='zones',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='membres',
        ),
        migrations.RemoveField(
            model_name='historicalactivite',
            name='responsable_nom',
        ),
        migrations.AddField(
            model_name='activite',
            name='responsables_noms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text="Noms des responsables — texte libre, un ou plusieurs, indépendants d'un compte plateforme.", size=None),
        ),
        migrations.AddField(
            model_name='equipe',
            name='membres_noms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text="Noms des membres de l'équipe — texte libre, un ou plusieurs.", size=None),
        ),
        migrations.AddField(
            model_name='historicalactivite',
            name='responsables_noms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text="Noms des responsables — texte libre, un ou plusieurs, indépendants d'un compte plateforme.", size=None),
        ),
        migrations.AddField(
            model_name='historicalequipe',
            name='membres_noms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text="Noms des membres de l'équipe — texte libre, un ou plusieurs.", size=None),
        ),
    ]
