# Generated by Django 5.0.14 on 2026-08-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_backfill_projets_associes_intervenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='date_debut_contrat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='date_fin_contrat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalequipe',
            name='date_debut_contrat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalequipe',
            name='date_fin_contrat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
