# Generated by Django 5.0.14 on 2026-08-20 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_bailleur_financement_and_more'),
        ('projects', '0016_equipe_dates_contrat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprojet',
            name='chef_de_projet',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='chef_de_projet',
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='partenaire_mise_en_oeuvre',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Partenaire de mise en œuvre principal (Partenaire.type=MISE_EN_OEUVRE).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.partenaire'),
        ),
        migrations.AddField(
            model_name='projet',
            name='partenaire_mise_en_oeuvre',
            field=models.ForeignKey(blank=True, help_text='Partenaire de mise en œuvre principal (Partenaire.type=MISE_EN_OEUVRE).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projets_mise_en_oeuvre', to='partners.partenaire'),
        ),
        migrations.AddField(
            model_name='projet',
            name='partenaires_consortium',
            field=models.ManyToManyField(blank=True, help_text='Partenaires du consortium — renseigné quand type_mise_en_oeuvre=CONSORTIUM.', related_name='projets_consortium', to='partners.partenaire'),
        ),
        migrations.AlterField(
            model_name='historicalprojet',
            name='chef_de_projet_nom',
            field=models.CharField(blank=True, help_text="Nom du chef de projet — texte libre, indépendant d'un compte plateforme. Pour donner accès à la plateforme, ajoute la personne dans « Utilisateurs affectés » ci-dessous.", max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalprojet',
            name='partenaire_bailleur',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Bailleur principal (Partenaire.type=BAILLEUR).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.partenaire'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='chef_de_projet_nom',
            field=models.CharField(blank=True, help_text="Nom du chef de projet — texte libre, indépendant d'un compte plateforme. Pour donner accès à la plateforme, ajoute la personne dans « Utilisateurs affectés » ci-dessous.", max_length=200),
        ),
        migrations.AlterField(
            model_name='projet',
            name='partenaire_bailleur',
            field=models.ForeignKey(blank=True, help_text='Bailleur principal (Partenaire.type=BAILLEUR).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='partners.partenaire'),
        ),
    ]
