# Generated by Django 5.0.14 on 2026-08-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_remove_historicalprojet_chef_de_projet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='valeur_reference',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Valeur de base avant le démarrage de l'activité — une activité se suit alors comme un indicateur (valeur de départ → cible), utile pour tracer la progression attendue dans le temps.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalactivite',
            name='valeur_reference',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Valeur de base avant le démarrage de l'activité — une activité se suit alors comme un indicateur (valeur de départ → cible), utile pour tracer la progression attendue dans le temps.", max_digits=12, null=True),
        ),
    ]
