# Generated by Django 5.0.14 on 2026-08-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_activite_valeur_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='date_rappel',
            field=models.DateField(blank=True, help_text="Date fixe à laquelle une alerte de rappel est déclenchée pour cette activité, indépendamment du seuil de jours avant l'échéance.", null=True),
        ),
        migrations.AddField(
            model_name='historicalactivite',
            name='date_rappel',
            field=models.DateField(blank=True, help_text="Date fixe à laquelle une alerte de rappel est déclenchée pour cette activité, indépendamment du seuil de jours avant l'échéance.", null=True),
        ),
        migrations.AddField(
            model_name='historicalprojet',
            name='date_rappel',
            field=models.DateField(blank=True, help_text="Date fixe à laquelle une alerte de rappel est déclenchée pour ce projet, indépendamment du seuil de jours avant l'échéance (ex : pour un rapport bailleur à une date précise).", null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_rappel',
            field=models.DateField(blank=True, help_text="Date fixe à laquelle une alerte de rappel est déclenchée pour ce projet, indépendamment du seuil de jours avant l'échéance (ex : pour un rapport bailleur à une date précise).", null=True),
        ),
    ]
