# Generated by Django 5.0.14 on 2026-08-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INDICATEUR_ALERTE', 'Indicateur en alerte'), ('RAPPORT_SOUMIS', 'Rapport soumis pour validation'), ('RAPPORT_VALIDE', 'Rapport validé'), ('DOUBLON_SIGNALE', 'Doublon bénéficiaire signalé'), ('ECHEANCE_ACTIVITE', "Échéance d'activité proche"), ('ACTIVITE_MODIFIEE', 'Activité planifiée modifiée')], max_length=30),
        ),
    ]
