# Generated by Django 5.0.14 on 2026-08-17 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_activite_axe_strategique_activite_budget_realise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('fonction', models.CharField(blank=True, help_text='Ex : Chef de projet, Animateur…', max_length=150)),
                ('contact', models.CharField(blank=True, max_length=150)),
                ('activites_associees', models.ManyToManyField(blank=True, related_name='intervenants', to='projects.activite')),
                ('projets_associes', models.ManyToManyField(blank=True, related_name='intervenants', to='projects.projet')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervenant_profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nom', 'prenom'),
            },
        ),
    ]
