# Generated by Django 5.0.14 on 2026-08-19 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0016_equipe_dates_contrat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('quantite_realisee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_realise', models.DecimalField(blank=True, decimal_places=2, help_text="Uniquement pertinent pour une activité — les sous-activités n'ont pas de budget propre.", max_digits=14, null=True)),
                ('statut', models.CharField(blank=True, help_text='Statut au moment de cette saisie (facultatif).', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='points_suivi', to='projects.activite')),
                ('saisi_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points_suivi_saisis', to=settings.AUTH_USER_MODEL)),
                ('sous_activite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='points_suivi', to='projects.sousactivite')),
            ],
            options={
                'verbose_name': 'Point de suivi',
                'verbose_name_plural': 'Points de suivi',
                'ordering': ('-periode_fin',),
            },
        ),
        migrations.AddConstraint(
            model_name='pointsuivi',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('activite__isnull', False), ('sous_activite__isnull', True)), models.Q(('activite__isnull', True), ('sous_activite__isnull', False)), _connector='OR'), name='point_suivi_rattachement_unique'),
        ),
        migrations.AddConstraint(
            model_name='pointsuivi',
            constraint=models.UniqueConstraint(condition=models.Q(('activite__isnull', False)), fields=('activite', 'periode_debut', 'periode_fin'), name='point_suivi_activite_periode_unique'),
        ),
        migrations.AddConstraint(
            model_name='pointsuivi',
            constraint=models.UniqueConstraint(condition=models.Q(('sous_activite__isnull', False)), fields=('sous_activite', 'periode_debut', 'periode_fin'), name='point_suivi_sous_activite_periode_unique'),
        ),
    ]
