# Generated by Django 5.0.14 on 2026-08-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('COORDO_GENERAL', 'Coordonnateur général'), ('CHARGE_SE', 'Chargé de Suivi-Évaluation'), ('CHEF_PROJET', 'Chef de projet'), ('CHEF_SERVICE', 'Chef de service'), ('ANIMATEUR_TERRAIN', 'Animateur de terrain')], max_length=32),
        ),
    ]
