# Generated by Django 5.0.14 on 2026-08-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='niveau_acces',
            field=models.CharField(choices=[('LECTURE_SEULE', 'Lecture seule'), ('LECTURE_ECRITURE', 'Lecture et écriture')], default='LECTURE_ECRITURE', help_text='Lecture seule = consultation uniquement ; Lecture et écriture = peut créer/modifier dans son périmètre. Un Administrateur a toujours un accès complet, indépendamment de ce champ.', max_length=20),
        ),
    ]
