# Generated by Django 5.0.14 on 2026-08-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('BAILLEUR', 'Bailleur'), ('MISE_EN_OEUVRE', 'Partenaire de mise en œuvre')], max_length=20)),
                ('contact', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
    ]
