# Generated by Django 5.0.14 on 2026-08-17 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('projects', '0002_activite_axe_strategique_activite_budget_realise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bailleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('INSTITUTIONNEL', 'Institutionnel'), ('FONDATION', 'Fondation'), ('COOPERATION_BILATERALE', 'Coopération bilatérale'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30)),
                ('contact', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Financement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant_finance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financements', to='partners.bailleur')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financements', to='projects.projet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='financement',
            constraint=models.UniqueConstraint(fields=('projet', 'bailleur'), name='financement_projet_bailleur_unique'),
        ),
    ]
