# Generated by Django 5.0.14 on 2026-08-17 10:22

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJustificative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fichier', models.FileField(upload_to=apps.documents.models.chemin_upload)),
                ('nom', models.CharField(max_length=200)),
                ('type_document', models.CharField(blank=True, max_length=100)),
                ('rapport_suivi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_justificatives', to='reports.rapportsuivi')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_uploades', to=settings.AUTH_USER_MODEL)),
                ('valeur_indicateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_justificatives', to='indicators.valeurindicateur')),
            ],
            options={
                'verbose_name': 'Pièce justificative',
                'verbose_name_plural': 'Pièces justificatives',
            },
        ),
        migrations.AddConstraint(
            model_name='piecejustificative',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('rapport_suivi__isnull', True), ('valeur_indicateur__isnull', False)), models.Q(('rapport_suivi__isnull', False), ('valeur_indicateur__isnull', True)), _connector='OR'), name='piece_justificative_rattachement_unique'),
        ),
    ]
