# Generated by Django 5.0.14 on 2026-08-17 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_documentversion_dossier_document_dossier_and_more'),
        ('projects', '0002_activite_axe_strategique_activite_budget_realise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_ged', to='projects.activite'),
        ),
    ]
