# Generated by Django 5.0.14 on 2026-09-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_activite'),
        ('indicators', '0011_alter_palieralerte_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='piecejustificative',
            name='piece_justificative_rattachement_unique',
        ),
        migrations.RemoveField(
            model_name='piecejustificative',
            name='rapport_suivi',
        ),
        migrations.AlterField(
            model_name='piecejustificative',
            name='valeur_indicateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_justificatives', to='indicators.valeurindicateur'),
        ),
    ]
