# Generated by Django 5.0.14 on 2026-09-18 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_piecejustificative_piece_justificative_rattachement_unique_and_more'),
        ('projects', '0019_activite_date_rappel_historicalactivite_date_rappel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sous_activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_ged', to='projects.sousactivite'),
        ),
    ]
