# Generated by Django 5.0.14 on 2026-08-17 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrientationStrategique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Ex : OS1', max_length=20)),
                ('libelle', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='PlanStrategique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('vision', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('budget_global', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-date_debut',),
            },
        ),
        migrations.CreateModel(
            name='AxeStrategique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_axe', models.CharField(help_text='Ex : 1.1', max_length=20)),
                ('libelle', models.CharField(max_length=300)),
                ('orientation_strategique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='axes_strategiques', to='strategy.orientationstrategique')),
            ],
            options={
                'ordering': ('code_axe',),
            },
        ),
        migrations.AddField(
            model_name='orientationstrategique',
            name='plan_strategique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orientations_strategiques', to='strategy.planstrategique'),
        ),
    ]
