# Generated by Django 5.0.14 on 2026-08-18 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='axestrategique',
            name='orientation_strategique',
        ),
        migrations.RemoveField(
            model_name='orientationstrategique',
            name='plan_strategique',
        ),
        migrations.CreateModel(
            name='TypeNiveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_niveau', models.CharField(help_text="Ex : 'Orientation stratégique', 'Priorité'...", max_length=150)),
                ('ordre', models.PositiveSmallIntegerField(help_text='Position dans la hiérarchie : 1 = niveau le plus élevé.', unique=True)),
                ('saut_niveau_autorise', models.BooleanField(default=False, help_text="Autorise un élément de ce niveau à avoir un parent qui n'est pas du niveau immédiatement supérieur.")),
                ('aide_code', models.CharField(blank=True, help_text="Exemple de code affiché comme aide à la saisie (ex : 'Ex : OS1').", max_length=100)),
                ('niveau_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='niveaux_enfants', to='strategy.typeniveau')),
            ],
            options={
                'ordering': ('ordre',),
            },
        ),
        migrations.CreateModel(
            name='ElementStrategique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('nom', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('element_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enfants', to='strategy.elementstrategique')),
                ('type_niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='strategy.typeniveau')),
            ],
            options={
                'ordering': ('type_niveau__ordre', 'code', 'nom'),
            },
        ),
    ]
