# Generated by Django 5.0.14 on 2026-08-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_indicateurelement_and_more'),
        ('projects', '0004_alter_activite_axe_strategique_and_more'),
        ('strategy', '0002_remove_axestrategique_orientation_strategique_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AxeStrategique',
        ),
        migrations.DeleteModel(
            name='OrientationStrategique',
        ),
        migrations.DeleteModel(
            name='PlanStrategique',
        ),
    ]
