# Generated by Django 5.0.14 on 2026-08-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_delete_axestrategique_delete_orientationstrategique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeniveau',
            name='ordre',
            field=models.PositiveSmallIntegerField(help_text='Position dans la hiérarchie : 1 = niveau le plus élevé.'),
        ),
    ]
