# Generated by Django 5.0.14 on 2026-08-18 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_alter_typeniveau_ordre'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadreStrategique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='typeniveau',
            options={'ordering': ('cadre_strategique', 'ordre')},
        ),
        migrations.AddField(
            model_name='typeniveau',
            name='cadre_strategique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types_niveaux', to='strategy.cadrestrategique'),
        ),
    ]
