# Generated by Django 5.0.14 on 2026-09-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_piecejustificative_piece_justificative_rattachement_unique_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapportsuivi',
            name='projet',
        ),
        migrations.RemoveField(
            model_name='rapportsuivi',
            name='redige_par',
        ),
        migrations.RemoveField(
            model_name='rapportsuivi',
            name='valide_par',
        ),
        migrations.DeleteModel(
            name='HistoricalRapportSuivi',
        ),
        migrations.DeleteModel(
            name='RapportSuivi',
        ),
    ]
