# Generated by Django 5.0.14 on 2026-08-17 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('PROVINCE', 'Province'), ('COMMUNE', 'Commune'), ('VILLAGE', 'Village')], max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enfants', to='geo.zone')),
            ],
            options={
                'verbose_name': "Zone d'intervention",
                'verbose_name_plural': "Zones d'intervention",
                'ordering': ('type', 'nom'),
            },
        ),
    ]
