# Generated by Django 5.0.14 on 2026-08-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='type',
            field=models.CharField(choices=[('REGION', 'Région'), ('PROVINCE', 'Province'), ('COMMUNE', 'Commune'), ('VILLAGE', 'Village')], max_length=20),
        ),
    ]
