# Generated by Django 5.0.14 on 2026-08-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_zone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Code administratif (pcode), si connu.', max_length=20),
        ),
    ]
