// Liste des pays du monde (codes ISO 3166-1 alpha-2 + nom français),
// triée alphabétiquement — sert de source pour le sélecteur "Pays
// d'intervention" du formulaire Projet (recherche + sélection multiple).
export const PAYS_MONDE: { code: string; nom: string }[] = [
  { code: "AF", nom: "Afghanistan" },
  { code: "ZA", nom: "Afrique du Sud" },
  { code: "AL", nom: "Albanie" },
  { code: "DZ", nom: "Algérie" },
  { code: "DE", nom: "Allemagne" },
  { code: "AD", nom: "Andorre" },
  { code: "AO", nom: "Angola" },
  { code: "AG", nom: "Antigua-et-Barbuda" },
  { code: "SA", nom: "Arabie saoudite" },
  { code: "AR", nom: "Argentine" },
  { code: "AM", nom: "Arménie" },
  { code: "AU", nom: "Australie" },
  { code: "AT", nom: "Autriche" },
  { code: "AZ", nom: "Azerbaïdjan" },
  { code: "BS", nom: "Bahamas" },
  { code: "BH", nom: "Bahreïn" },
  { code: "BD", nom: "Bangladesh" },
  { code: "BB", nom: "Barbade" },
  { code: "BE", nom: "Belgique" },
  { code: "BZ", nom: "Belize" },
  { code: "BJ", nom: "Bénin" },
  { code: "BT", nom: "Bhoutan" },
  { code: "BY", nom: "Biélorussie" },
  { code: "MM", nom: "Birmanie (Myanmar)" },
  { code: "BO", nom: "Bolivie" },
  { code: "BA", nom: "Bosnie-Herzégovine" },
  { code: "BW", nom: "Botswana" },
  { code: "BR", nom: "Brésil" },
  { code: "BN", nom: "Brunei" },
  { code: "BG", nom: "Bulgarie" },
  { code: "BF", nom: "Burkina Faso" },
  { code: "BI", nom: "Burundi" },
  { code: "KH", nom: "Cambodge" },
  { code: "CM", nom: "Cameroun" },
  { code: "CA", nom: "Canada" },
  { code: "CV", nom: "Cap-Vert" },
  { code: "CL", nom: "Chili" },
  { code: "CN", nom: "Chine" },
  { code: "CY", nom: "Chypre" },
  { code: "CO", nom: "Colombie" },
  { code: "KM", nom: "Comores" },
  { code: "CG", nom: "Congo" },
  { code: "CD", nom: "Congo (RDC)" },
  { code: "KR", nom: "Corée du Sud" },
  { code: "KP", nom: "Corée du Nord" },
  { code: "CR", nom: "Costa Rica" },
  { code: "CI", nom: "Côte d'Ivoire" },
  { code: "HR", nom: "Croatie" },
  { code: "CU", nom: "Cuba" },
  { code: "DK", nom: "Danemark" },
  { code: "DJ", nom: "Djibouti" },
  { code: "DM", nom: "Dominique" },
  { code: "EG", nom: "Égypte" },
  { code: "AE", nom: "Émirats arabes unis" },
  { code: "EC", nom: "Équateur" },
  { code: "ER", nom: "Érythrée" },
  { code: "ES", nom: "Espagne" },
  { code: "EE", nom: "Estonie" },
  { code: "SZ", nom: "Eswatini" },
  { code: "US", nom: "États-Unis" },
  { code: "ET", nom: "Éthiopie" },
  { code: "FJ", nom: "Fidji" },
  { code: "FI", nom: "Finlande" },
  { code: "FR", nom: "France" },
  { code: "GA", nom: "Gabon" },
  { code: "GM", nom: "Gambie" },
  { code: "GE", nom: "Géorgie" },
  { code: "GH", nom: "Ghana" },
  { code: "GR", nom: "Grèce" },
  { code: "GD", nom: "Grenade" },
  { code: "GT", nom: "Guatemala" },
  { code: "GN", nom: "Guinée" },
  { code: "GQ", nom: "Guinée équatoriale" },
  { code: "GW", nom: "Guinée-Bissau" },
  { code: "GY", nom: "Guyana" },
  { code: "HT", nom: "Haïti" },
  { code: "HN", nom: "Honduras" },
  { code: "HU", nom: "Hongrie" },
  { code: "IN", nom: "Inde" },
  { code: "ID", nom: "Indonésie" },
  { code: "IQ", nom: "Irak" },
  { code: "IR", nom: "Iran" },
  { code: "IE", nom: "Irlande" },
  { code: "IS", nom: "Islande" },
  { code: "IL", nom: "Israël" },
  { code: "IT", nom: "Italie" },
  { code: "JM", nom: "Jamaïque" },
  { code: "JP", nom: "Japon" },
  { code: "JO", nom: "Jordanie" },
  { code: "KZ", nom: "Kazakhstan" },
  { code: "KE", nom: "Kenya" },
  { code: "KG", nom: "Kirghizistan" },
  { code: "KI", nom: "Kiribati" },
  { code: "XK", nom: "Kosovo" },
  { code: "KW", nom: "Koweït" },
  { code: "LA", nom: "Laos" },
  { code: "LS", nom: "Lesotho" },
  { code: "LV", nom: "Lettonie" },
  { code: "LB", nom: "Liban" },
  { code: "LR", nom: "Libéria" },
  { code: "LY", nom: "Libye" },
  { code: "LI", nom: "Liechtenstein" },
  { code: "LT", nom: "Lituanie" },
  { code: "LU", nom: "Luxembourg" },
  { code: "MK", nom: "Macédoine du Nord" },
  { code: "MG", nom: "Madagascar" },
  { code: "MY", nom: "Malaisie" },
  { code: "MW", nom: "Malawi" },
  { code: "MV", nom: "Maldives" },
  { code: "ML", nom: "Mali" },
  { code: "MT", nom: "Malte" },
  { code: "MA", nom: "Maroc" },
  { code: "MH", nom: "Îles Marshall" },
  { code: "MU", nom: "Maurice" },
  { code: "MR", nom: "Mauritanie" },
  { code: "MX", nom: "Mexique" },
  { code: "FM", nom: "Micronésie" },
  { code: "MD", nom: "Moldavie" },
  { code: "MC", nom: "Monaco" },
  { code: "MN", nom: "Mongolie" },
  { code: "ME", nom: "Monténégro" },
  { code: "MZ", nom: "Mozambique" },
  { code: "NA", nom: "Namibie" },
  { code: "NR", nom: "Nauru" },
  { code: "NP", nom: "Népal" },
  { code: "NI", nom: "Nicaragua" },
  { code: "NE", nom: "Niger" },
  { code: "NG", nom: "Nigéria" },
  { code: "NO", nom: "Norvège" },
  { code: "NZ", nom: "Nouvelle-Zélande" },
  { code: "OM", nom: "Oman" },
  { code: "UG", nom: "Ouganda" },
  { code: "UZ", nom: "Ouzbékistan" },
  { code: "PK", nom: "Pakistan" },
  { code: "PW", nom: "Palaos" },
  { code: "PS", nom: "Palestine" },
  { code: "PA", nom: "Panama" },
  { code: "PG", nom: "Papouasie-Nouvelle-Guinée" },
  { code: "PY", nom: "Paraguay" },
  { code: "NL", nom: "Pays-Bas" },
  { code: "PE", nom: "Pérou" },
  { code: "PH", nom: "Philippines" },
  { code: "PL", nom: "Pologne" },
  { code: "PT", nom: "Portugal" },
  { code: "QA", nom: "Qatar" },
  { code: "RO", nom: "Roumanie" },
  { code: "GB", nom: "Royaume-Uni" },
  { code: "RU", nom: "Russie" },
  { code: "RW", nom: "Rwanda" },
  { code: "KN", nom: "Saint-Christophe-et-Niévès" },
  { code: "SM", nom: "Saint-Marin" },
  { code: "VC", nom: "Saint-Vincent-et-les-Grenadines" },
  { code: "LC", nom: "Sainte-Lucie" },
  { code: "SB", nom: "Salomon" },
  { code: "SV", nom: "Salvador" },
  { code: "WS", nom: "Samoa" },
  { code: "ST", nom: "Sao Tomé-et-Principe" },
  { code: "SN", nom: "Sénégal" },
  { code: "RS", nom: "Serbie" },
  { code: "SC", nom: "Seychelles" },
  { code: "SL", nom: "Sierra Leone" },
  { code: "SG", nom: "Singapour" },
  { code: "SK", nom: "Slovaquie" },
  { code: "SI", nom: "Slovénie" },
  { code: "SO", nom: "Somalie" },
  { code: "SD", nom: "Soudan" },
  { code: "SS", nom: "Soudan du Sud" },
  { code: "LK", nom: "Sri Lanka" },
  { code: "SE", nom: "Suède" },
  { code: "CH", nom: "Suisse" },
  { code: "SR", nom: "Suriname" },
  { code: "SY", nom: "Syrie" },
  { code: "TJ", nom: "Tadjikistan" },
  { code: "TW", nom: "Taïwan" },
  { code: "TZ", nom: "Tanzanie" },
  { code: "TD", nom: "Tchad" },
  { code: "CZ", nom: "Tchéquie" },
  { code: "TH", nom: "Thaïlande" },
  { code: "TL", nom: "Timor oriental" },
  { code: "TG", nom: "Togo" },
  { code: "TO", nom: "Tonga" },
  { code: "TT", nom: "Trinité-et-Tobago" },
  { code: "TN", nom: "Tunisie" },
  { code: "TM", nom: "Turkménistan" },
  { code: "TR", nom: "Turquie" },
  { code: "TV", nom: "Tuvalu" },
  { code: "UA", nom: "Ukraine" },
  { code: "UY", nom: "Uruguay" },
  { code: "VU", nom: "Vanuatu" },
  { code: "VA", nom: "Vatican" },
  { code: "VE", nom: "Venezuela" },
  { code: "VN", nom: "Vietnam" },
  { code: "YE", nom: "Yémen" },
  { code: "ZM", nom: "Zambie" },
  { code: "ZW", nom: "Zimbabwe" },
];
