# Generated by Django 5.0.14 on 2026-08-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0003_beneficiaire_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbeneficiaire',
            name='pays',
            field=models.CharField(blank=True, help_text='Code ISO 3166-1 alpha-2 du pays (ex : BF, ML, NE).', max_length=2),
        ),
    ]
