# Generated by Django 5.0.14 on 2026-09-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0004_historicalbeneficiaire_pays'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeActiviteBeneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': "Type d'activité du bénéficiaire",
                'verbose_name_plural': "Types d'activité des bénéficiaires",
                'ordering': ('libelle',),
            },
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='types_activite',
            field=models.ManyToManyField(blank=True, help_text='Activité(s) économique(s) menée(s) par le bénéficiaire (maraîchage, élevage...).', related_name='beneficiaires', to='beneficiaries.typeactivitebeneficiaire'),
        ),
    ]
