# Generated by hand on 2026-09-10
"""
Pré-remplit le référentiel « Type d'activité du bénéficiaire » avec quelques
activités économiques courantes en contexte rural sahélien — un utilisateur
peut toujours en créer d'autres à la volée depuis la fiche bénéficiaire si
celle qu'il cherche n'y figure pas.
"""
from django.db import migrations


TYPES_PAR_DEFAUT = [
    ("MARAICHAGE", "Maraîchage"),
    ("ELEVAGE", "Élevage"),
    ("AGRICULTURE_PLUVIALE", "Agriculture pluviale"),
    ("PETIT_COMMERCE", "Petit commerce"),
    ("TRANSFORMATION_AGROALIMENTAIRE", "Transformation agroalimentaire"),
    ("ARTISANAT", "Artisanat"),
]


def seed_types(apps, schema_editor):
    TypeActiviteBeneficiaire = apps.get_model("beneficiaries", "TypeActiviteBeneficiaire")
    if TypeActiviteBeneficiaire.objects.exists():
        return
    TypeActiviteBeneficiaire.objects.bulk_create(
        [TypeActiviteBeneficiaire(code=code, libelle=libelle) for code, libelle in TYPES_PAR_DEFAUT]
    )


def revert(apps, schema_editor):
    TypeActiviteBeneficiaire = apps.get_model("beneficiaries", "TypeActiviteBeneficiaire")
    TypeActiviteBeneficiaire.objects.filter(code__in=[code for code, _ in TYPES_PAR_DEFAUT]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0005_typeactivitebeneficiaire_beneficiaire_types_activite"),
    ]

    operations = [
        migrations.RunPython(seed_types, revert),
    ]
