# Generated by Django 5.0.14 on 2026-09-18 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0006_seed_types_activite_beneficiaire'),
        ('projects', '0019_activite_date_rappel_historicalactivite_date_rappel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparticipationprojet',
            name='activite',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.activite'),
        ),
        migrations.AddField(
            model_name='historicalparticipationprojet',
            name='sous_activite',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.sousactivite'),
        ),
        migrations.AddField(
            model_name='participationprojet',
            name='activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='projects.activite'),
        ),
        migrations.AddField(
            model_name='participationprojet',
            name='sous_activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='projects.sousactivite'),
        ),
    ]
